### ISSUE TITLE
07 - 01 - Reactified Octocats

### ISSUE THREAD

**Issue by ColterLena** [ColterLena/assignments#24]
The Octodex is a fun way to celebrate a powerful tool we use for development. In that same spirit, recreate [this site](https://octodex.github.com/)

You'll identify the main `Component`s on the page and create React components for each, breaking down those `Component`s into smaller ones as needed.

## Objectives

- Learn to identify parts of a web site as `Component`s
- Use `app-app` (GAMMA stack) to build a React project
- Understand and use React components

## Stretch Objectives

- Understand and use "props" in React

### Explorer Mode

- [ ] Create your React app using `app-app` `GAMMA`
- [ ] If you have done the non-React version of octodex, use your existing HTML as the `render()` method of your `App` component. Otherwise, figure out the main components of the page and implement the `render()` method of `App`
- [ ] Your CSS should be in `index.css` -- feel free to copy your previous project's css if you have done the non-React version of this assignment.
- [ ] You should have at _least_ two components... (Hint, perhaps Header, and an Octocat)
- [ ] Use props to try to reuse components (reuse the Octocat component)

### Adventure Mode

- [ ] Place the definition of each Octocat in an `array` of objects and use `map` to generate the Octocat components

### Epic Mode

- [ ] Put the `array` of Octocats in an `octocats.json` file and `import` that into your app.
- _OR_
- [ ] Use the `fetch` API to retrieve the list of Octocats from [this api](https://sdg-octodex.herokuapp.com/) instead

## Additional Resources

- [React Documentation](https://reactjs.org/docs/getting-started.html)
- [.map, .reduce & .filter, Oh My!](https://www.datchley.name/working-with-collections/)
- [Array.prototype.map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map)

**Comment by ColterLena** [comment]
https://github.com/ColterLena/reactified-octocats

**Comment by ColterLena** [comment]
Your homework **07 - 01 - Reactified Octocats** was marked: **Meets Expectations**


![Yas](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBDQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--eb161dfb00865249fe33bc4a730793f1eef22b19/neil.gif)
> &ldquo;Yas&rdquo;

**Comment by gstark** [comment]
Nicely done!

I'd challenge you to incorporate this part of the octocat into your `Octocat` component as well:

```
<ul>
              <li className="octocat-name-list-item">#150: Octoqueer</li>
              <li>
                <a href="https://github.com/cameronfoxly">
                  <img src="https://github.com/cameronfoxly.png" />
                </a>
              </li>
              <li>
                <a href="https://github.com/johncreek">
                  <img src="https://github.com/johncreek.png" />
                </a>
              </li>
              <li>
                <a href="https://github.com/tonyjaramillo">
                  <img src="https://github.com/tonyjaramillo.png" />
                </a>
              </li>
            </ul>
```

I'm accepting this as complete since you demonstrate the goal of the lesson but I invite you to revisit it and see if you can incorporate *all* of the rendering of the elements of an octocat into your component. Come ask questions if you are unsure.
